version: '3'

services:
    brevetsapp:
        build: brevets/
        volumes:
            - brevets/:/app/brevets
        command: python -u flask_brevets.py
        ports:
            - "6127:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    restapi:
        build: api/
        volumes:
            - api/:/app/api
        command: python -u api.py
        ports:
            - "6227:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    website:
        build: website/
        volumes:
            - website/:/app/website
        command: python -u website.py
        ports:
            - "6327:5000"
        depends_on:
            - restapi
    ourdb:
        image: mongo:latest
